name: flutter_adaptive_sidebar_example
description: Example app that switches Material and Cupertino sidebars.
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_adaptive_sidebar:
    path: ../
  ios_window_control_layout: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
